version: "3.9"
services:

  file-storage-db:
    container_name: file-storage-db
    image: postgres:16.0
    env_file:
      - .env.db
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "${DB_NAME}", "-U", "${DB_USER}" ]
      interval: 5s
      timeout: 3s
      retries: 5
    command: postgres -c 'max_connections=500'
    restart: unless-stopped
    networks:
      - storage
    ports:
      - "5435:5432"
    volumes:
      - db-volume:/var/lib/postgresql/data
  
  service:
    container_name: file-storage
    build:
      context: .
      dockerfile: Dockerfile
    image: file-storage
    env_file:
      - .env.prod
    depends_on:
      nri-db:
        condition: service_healthy
    command:
      - /bin/sh
      - -c
      - |
        alembic upgrade head
        python helpers/data_filler_from_sql.py
        uvicorn app.main:app --host=0.0.0.0 --port=8000
    networks:
      acsfer:
    ports:
      - "8001:8000"

volumes:
  db-volume:
    name: file-storage-db-volume

networks:
  file-storage:
    name: storage
